
package com.avalon.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceWSDLController2Service", targetNamespace = "http://webservice.avalon.com/", wsdlLocation = "http://localhost:9090/webservice/WebServiceWSDLController2?wsdl")
public class WebServiceWSDLController2Service
    extends Service
{

    private final static URL WEBSERVICEWSDLCONTROLLER2SERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEWSDLCONTROLLER2SERVICE_EXCEPTION;
    private final static QName WEBSERVICEWSDLCONTROLLER2SERVICE_QNAME = new QName("http://webservice.avalon.com/", "WebServiceWSDLController2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/webservice/WebServiceWSDLController2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEWSDLCONTROLLER2SERVICE_WSDL_LOCATION = url;
        WEBSERVICEWSDLCONTROLLER2SERVICE_EXCEPTION = e;
    }

    public WebServiceWSDLController2Service() {
        super(__getWsdlLocation(), WEBSERVICEWSDLCONTROLLER2SERVICE_QNAME);
    }

    public WebServiceWSDLController2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEWSDLCONTROLLER2SERVICE_QNAME, features);
    }

    public WebServiceWSDLController2Service(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEWSDLCONTROLLER2SERVICE_QNAME);
    }

    public WebServiceWSDLController2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEWSDLCONTROLLER2SERVICE_QNAME, features);
    }

    public WebServiceWSDLController2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceWSDLController2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceWSDLController2
     */
    @WebEndpoint(name = "WebServiceWSDLController2Port")
    public WebServiceWSDLController2 getWebServiceWSDLController2Port() {
        return super.getPort(new QName("http://webservice.avalon.com/", "WebServiceWSDLController2Port"), WebServiceWSDLController2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceWSDLController2
     */
    @WebEndpoint(name = "WebServiceWSDLController2Port")
    public WebServiceWSDLController2 getWebServiceWSDLController2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.avalon.com/", "WebServiceWSDLController2Port"), WebServiceWSDLController2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEWSDLCONTROLLER2SERVICE_EXCEPTION!= null) {
            throw WEBSERVICEWSDLCONTROLLER2SERVICE_EXCEPTION;
        }
        return WEBSERVICEWSDLCONTROLLER2SERVICE_WSDL_LOCATION;
    }

}
