
package com.avalon.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceWSDLController2", targetNamespace = "http://webservice.avalon.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceWSDLController2 {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnString", targetNamespace = "http://webservice.avalon.com/", className = "com.avalon.webservice.ReturnString")
    @ResponseWrapper(localName = "returnStringResponse", targetNamespace = "http://webservice.avalon.com/", className = "com.avalon.webservice.ReturnStringResponse")
    @Action(input = "http://webservice.avalon.com/WebServiceWSDLController2/returnStringRequest", output = "http://webservice.avalon.com/WebServiceWSDLController2/returnStringResponse")
    public String returnString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
