
package org.slry.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChooseSLRYService", targetNamespace = "http://webservice.slry.org/", wsdlLocation = "http://60.191.102.221:8096/webServiceZJ/ChooseSLRYPort?wsdl")
public class ChooseSLRYService
    extends Service
{

    private final static URL CHOOSESLRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHOOSESLRYSERVICE_EXCEPTION;
    private final static QName CHOOSESLRYSERVICE_QNAME = new QName("http://webservice.slry.org/", "ChooseSLRYService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://60.191.102.221:8096/webServiceZJ/ChooseSLRYPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHOOSESLRYSERVICE_WSDL_LOCATION = url;
        CHOOSESLRYSERVICE_EXCEPTION = e;
    }

    public ChooseSLRYService() {
        super(__getWsdlLocation(), CHOOSESLRYSERVICE_QNAME);
    }

    public ChooseSLRYService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHOOSESLRYSERVICE_QNAME, features);
    }

    public ChooseSLRYService(URL wsdlLocation) {
        super(wsdlLocation, CHOOSESLRYSERVICE_QNAME);
    }

    public ChooseSLRYService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHOOSESLRYSERVICE_QNAME, features);
    }

    public ChooseSLRYService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChooseSLRYService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChooseSLRYDelegate
     */
    @WebEndpoint(name = "ChooseSLRYPort")
    public ChooseSLRYDelegate getChooseSLRYPort() {
        return super.getPort(new QName("http://webservice.slry.org/", "ChooseSLRYPort"), ChooseSLRYDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChooseSLRYDelegate
     */
    @WebEndpoint(name = "ChooseSLRYPort")
    public ChooseSLRYDelegate getChooseSLRYPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.slry.org/", "ChooseSLRYPort"), ChooseSLRYDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHOOSESLRYSERVICE_EXCEPTION!= null) {
            throw CHOOSESLRYSERVICE_EXCEPTION;
        }
        return CHOOSESLRYSERVICE_WSDL_LOCATION;
    }

}
