
package org.slry.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChooseSLRYDelegate", targetNamespace = "http://webservice.slry.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChooseSLRYDelegate {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSlryXX", targetNamespace = "http://webservice.slry.org/", className = "org.slry.webservice.GetSlryXX")
    @ResponseWrapper(localName = "getSlryXXResponse", targetNamespace = "http://webservice.slry.org/", className = "org.slry.webservice.GetSlryXXResponse")
    public String getSlryXX(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
